typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  dir
  vcs
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
)

typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''

typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''

typeset -g POWERLEVEL9K_DIR_FOREGROUND=250
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=108
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=173

typeset -g POWERLEVEL9K_DIR_BACKGROUND=
typeset -g POWERLEVEL9K_VCS_BACKGROUND=

typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true

typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='❯'

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_FOREGROUND=108
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_FOREGROUND=203

typeset -g POWERLEVEL9K_STATUS_OK=false

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
