---
- name: Setup Arch Linux packages and dotfiles
  hosts: localhost
  connection: local
  become: true
  vars:
    jpgwallpaper: "wallhaven-k81776.jpg"
    pacman_packages:
      - base-devel
      - git
      - vim
      - tmux
      - ansible
      - hyprland
      - waybar
      - alacritty
      - rofi-wayland
      - sddm
      - greetd
      - nwg-hello
      - wl-clipboard
      - grim
      - slurp
      - swappy
      - ttf-jetbrains-mono-nerd
      - swaybg
      - nwg-look
      - cage
      - swaylock
#      - noto-fonts-emoji`
      - pamixer
      - brightnessctl
      - zsh
      - neovim
    dotfiles:
      # Add dotfile entries here with src/dest pairs.
      # Example:
      # - src: "dotfiles/.bashrc"
      #   dest: "/home/{{ ansible_user_id }}/.bashrc"
      - src: "dotfiles/.bashrc"
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.bashrc"
      - src: "dotfiles/.config/alacritty/alacritty.toml"
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.config/alacritty/alacritty.toml"
      - src: "dotfiles/.config/alacritty/themes"
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.config/alacritty/"
      - src: "dotfiles/.vimrc"
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.vimrc"
      - src: "dotfiles/.config/hypr"
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.config/"
      - src: "dotfiles/.config/waybar"
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.config/"
      - src: "dotfiles/.config/rofi"
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.config/"
      - src: "dotfiles/.zshrc"
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.zshrc"
      - src: "dotfiles/.p10k.zsh"
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.p10k.zsh"
      - src: "dotfiles/.zsh"
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.zsh/"
      - src: "dotfiles/.config/nvim"
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.config/nvim/"
    otherfiles:
      - src: "configfiles/greetd_config.toml"
        dest: "/etc/greetd/config.toml"
      - src: "configfiles/nwg-hello.json"
        dest: "/etc/nwg-hello/nwg-hello.json"
      - src: "configfiles/nwg-hello.css"
        dest: "/etc/nwg-hello/nwg-hello.css"
      - src: "configfiles/nwg-hello.hyprland.lua"
        dest: "/etc/nwg-hello/hyprland.lua"
      - src: "{{ jpgwallpaper }}"
        dest: "/usr/share/backgrounds/wallpaper.jpg"
  tasks:
    - name: Update pacman packages
      pacman:
        upgrade: yes
        update_cache: yes

    - name: Install pacman packages
      pacman:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ pacman_packages }}"

    - name: Copy dotfiles to target locations
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ lookup('ansible.builtin.env', 'SUDO_USER') }}"
        mode: preserve
      loop: "{{ dotfiles }}"
      when: dotfiles | length > 0

    - name: Copy other files to target locations
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ lookup('ansible.builtin.env', 'SUDO_USER') }}"
        mode: preserve
      loop: "{{ otherfiles }}"
      when: otherfiles | length > 0

    - name: Disable lightdm
      systemd_service:
        name: "lightdm"
        enabled: false

    - name: Enable greetd
      systemd_service:
        name: "greetd"
        enabled: true

    - name: Change shell to zsh
      tags: zsh
      user:
        user: "{{ lookup('ansible.builtin.env', 'SUDO_USER') }}"
        shell: "/usr/bin/zsh"

    - name: Clone powerlevel10k
      tags: zsh
      ansible.builtin.git:
        repo: 'https://github.com/romkatv/powerlevel10k.git'
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.zsh/powerlevel10k"

    - name: Clone zsh-autosuggestions
      tags: zsh
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions'
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.zsh/zsh-autosuggestions"

    - name: Clone zsh-syntax-highlighting
      tags: zsh
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
        dest: "{{ lookup('ansible.builtin.env', 'SUDO_HOME') }}/.zsh/zsh-syntax-highlighting"
