# Only deployed on hosts with enable_suspend (see vars.yml)
general {
    lock_cmd = pidof swaylock || swaylock -f -c 000000
    before_sleep_cmd = loginctl lock-session
}

# Lock after 5 minutes idle
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Suspend after 10 minutes idle
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
