# GTK theme (use nwg-look later to tweak visually)
theme = "Adwaita-dark"

# Command to start Hyprland after login
command = "Hyprland"

# Background (optional)
background = "/usr/share/backgrounds/wallpaper.jpg"

# Time format
clock-format = "%H:%M"

# Cursor theme (optional)
cursor-theme = "Adwaita"
